<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMQzNi46\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMQzNi46/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMQzNi46.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMQzNi46\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMQzNi46\App_KernelDevDebugContainer([
    'container.build_hash' => 'MQzNi46',
    'container.build_id' => '3e4b42ba',
    'container.build_time' => 1696073729,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMQzNi46');
